config/routes.rb
WorkKiller::Application.routes.draw do
  devise_for :users

  resources :word_lists

  # You can have the root of your site routed with "root"
  root 'word_lists#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable,
         :registerable # Users don't register themselves

  has_many :word_lists
  
  validates :user_name, :presence => true, :uniqueness => true
  
  def role_symbols
    [ :user ]
  end
end

app/models/word_list.rb
class WordList < ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true, :uniqueness => true
  validates :user_id, :presence => true
  validates :good_words, :presence => true
  validates :bad_words, :presence => true
  
  scope :ordered, -> { order("LOWER(name)") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  protected
    def update_sanitized_params
      devise_parameter_sanitizer.for(:sign_up) << :user_name
      devise_parameter_sanitizer.for(:account_update) << :user_name
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/controllers/word_lists_controller.rb
class WordListsController < InheritedResources::Base
  respond_to :html, :json
  filter_resource_access

  def index
    if request.format == 'json'
      Settings.play_count += 1
      Settings.last_played = Time.now
    else
      @play_count  = Settings.play_count
      @play_count_since = Settings.play_count_since.to_date
      @last_played = Settings.last_played
    end
    
    index!
  end

  def create
    # @word_list created by filter_resource_access
    @word_list.user = current_user
    
    create!
  end

  protected

  def collection
    @word_lists ||= end_of_association_chain.ordered
  end

  def permitted_params
    { word_list: params.fetch(:word_list, {}).permit(:name, :good_words, :bad_words) }
  end

  def new_word_list_from_params
    @word_list = WordList.new(permitted_params[:word_list])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title, show_title = true)
    content_for :title, page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end

  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.simple_fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def lesc(text)
    LatexToPdf.escape_latex(text).force_encoding('UTF-8')
  end
  
  def textilize(text)
    Textilizer.new(text).to_html.html_safe unless text.blank?
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/word_lists_helper.rb
module WordListsHelper
end

app/views/layouts/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-<%= flash_class(level) %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html{lang: "de"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "#{'DEV ' if Rails.env.development? }Mr K.'s WordKiller"
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      -# .navbar-inner
      .container
        .navbar-header
          %button.navbar-toggle{type: "button"}(data-target=".navbar-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{ href: root_url } WordKiller List Manager
        %ul.nav.navbar-nav.pull-right
          - if signed_in?
            %li.dropdown{ class: @active == :user && 'active' }
              %a.dropdown-toggle(data-toggle='dropdown' href='#')
                %i.icon-user
                = current_user.user_name
                %span.caret
              %ul.dropdown-menu
                %li= link_to "<i class='icon-calendar'></i> Settings".html_safe, edit_user_registration_path(current_user)
                %li= link_to "<i class='icon-signout'></i> Log Out!".html_safe, destroy_user_session_path, method: :delete
          - else
            %li.inverse= link_to "<i class='icon-signin'></i> Log In".html_safe, new_user_session_path
        - if false
          .navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li{ class: @active == :users && 'active' }= link_to "Ritter", root_path
              - if signed_in?
                %li{ class: @active == :quests && 'active' }= link_to "Gesuche", root_path
              - else
                %li= link_to "Hilfe!", root_path

    .container
      .row
        .span12
          - if show_title?
            %h1.pagetitle= h yield(:title)
          = render 'layouts/messages'
          
          = yield
      - if false
        .footer.inline-list
          %ul
            %li= link_to "...", root_path
            %li
              %span.copyright
                &copy; 1866-2013 M. Kühnert,
                = link_to "Mr K.'s Homepage", 'http://www.mister-k.net', target: :new

app/views/welcome/hello.html.haml
%h1 Welcome#hello

%p
  Find me in app/views/welcome/hello.html.haml

app/views/word_lists/_form.html.haml
= simple_form_for(@word_list) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :good_words, input_html: { rows: 20 }
    = f.input :bad_words, input_html: { rows: 20 }

  .form-actions
    = f.button :submit

app/views/word_lists/edit.html.haml
%h1 Editing Wordlist

= render 'form'

%p
  = link_to 'Show', @word_list
  \|
  = link_to 'Back', word_lists_path

app/views/word_lists/index.html.haml
%h1 All Word Lists

%table.table
  %tr
    %th Name
    %th User
    %th Last Update
    %th Good words
    %th Bad words
    - if permitted_to? :edit, :word_lists
      %th Actions

  - @word_lists.each do |word_list|
    %tr
      %td= link_to word_list.name, word_list
      %td= word_list.user.user_name rescue 'Unknown User'
      %td= l word_list.updated_at
      %td= truncate word_list.good_words, length: 20
      %td= truncate word_list.bad_words, length: 20
      - if permitted_to? :edit, word_list
        %td
          = link_to 'Edit', edit_word_list_path(word_list)
          = link_to 'Destroy', word_list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

- if permitted_to? :create, :word_lists
  %p
    = link_to 'New Word list', new_word_list_path

%hr
%center
  This game has been played
  %b= @play_count
  times since 
  %b= l @play_count_since
  \.
  %br
  Last played: 
  %b= l @last_played
  \.

app/views/word_lists/new.html.haml
%h1 New Word List

= render 'form'

= link_to 'Back', word_lists_path

app/views/word_lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @word_list.name

%p
  %b User:
  = @word_list.user.user_name rescue 'Unknown User'

%p
  %b Good words:
  = @word_list.good_words

%p
  %b Bad words:
  = @word_list.bad_words

%p
  - if permitted_to? :edit, @word_list
    = link_to 'Edit', edit_word_list_path(@word_list)
    \|
  = link_to 'Back', word_lists_path